# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camtrak.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.solve_pnp_btn = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/icons/world_points.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.solve_pnp_btn.setIcon(icon)
        self.solve_pnp_btn.setIconSize(QtCore.QSize(32, 32))
        self.solve_pnp_btn.setObjectName("solve_pnp_btn")
        self.gridLayout.addWidget(self.solve_pnp_btn, 8, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.known_geo_points_tbl = QtWidgets.QTableWidget(self.groupBox)
        self.known_geo_points_tbl.setGeometry(QtCore.QRect(10, 30, 221, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.known_geo_points_tbl.sizePolicy().hasHeightForWidth())
        self.known_geo_points_tbl.setSizePolicy(sizePolicy)
        self.known_geo_points_tbl.setObjectName("known_geo_points_tbl")
        self.known_geo_points_tbl.setColumnCount(0)
        self.known_geo_points_tbl.setRowCount(0)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.capture_btn = QtWidgets.QToolButton(self.centralwidget)
        self.capture_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/assets/icons/capture_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.capture_btn.setIcon(icon1)
        self.capture_btn.setIconSize(QtCore.QSize(32, 32))
        self.capture_btn.setObjectName("capture_btn")
        self.gridLayout.addWidget(self.capture_btn, 10, 3, 1, 1)
        self.image_type_box = QtWidgets.QComboBox(self.centralwidget)
        self.image_type_box.setObjectName("image_type_box")
        self.image_type_box.addItem("")
        self.image_type_box.addItem("")
        self.image_type_box.addItem("")
        self.image_type_box.addItem("")
        self.gridLayout.addWidget(self.image_type_box, 11, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 321, 291))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.camera_lat_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.camera_lat_line.setDecimals(6)
        self.camera_lat_line.setMinimum(-180.0)
        self.camera_lat_line.setMaximum(178.0)
        self.camera_lat_line.setSingleStep(0.01)
        self.camera_lat_line.setProperty("value", -158.849411)
        self.camera_lat_line.setObjectName("camera_lat_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera_lat_line)
        self.camera_lon_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.camera_lon_line.setDecimals(6)
        self.camera_lon_line.setMinimum(-90.0)
        self.camera_lon_line.setMaximum(90.0)
        self.camera_lon_line.setSingleStep(0.01)
        self.camera_lon_line.setProperty("value", 21.304612)
        self.camera_lon_line.setObjectName("camera_lon_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera_lon_line)
        self.camera_alt_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.camera_alt_line.setDecimals(3)
        self.camera_alt_line.setMinimum(-1094.0)
        self.camera_alt_line.setMaximum(357860000.0)
        self.camera_alt_line.setProperty("value", 0.0)
        self.camera_alt_line.setObjectName("camera_alt_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera_alt_line)
        self.camera_ifov_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.camera_ifov_line.setDecimals(6)
        self.camera_ifov_line.setMaximum(360.0)
        self.camera_ifov_line.setSingleStep(0.01)
        self.camera_ifov_line.setProperty("value", 1.0)
        self.camera_ifov_line.setObjectName("camera_ifov_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.camera_ifov_line)
        self.cx_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cx_line.setDecimals(6)
        self.cx_line.setMaximum(10000.0)
        self.cx_line.setObjectName("cx_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cx_line)
        self.cy_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cy_line.setDecimals(6)
        self.cy_line.setMaximum(10000.0)
        self.cy_line.setObjectName("cy_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cy_line)
        self.phi_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.phi_line.setDecimals(6)
        self.phi_line.setMinimum(-180.0)
        self.phi_line.setMaximum(180.0)
        self.phi_line.setSingleStep(0.1)
        self.phi_line.setObjectName("phi_line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.phi_line)
        self.theta_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.theta_line.setDecimals(6)
        self.theta_line.setMinimum(-180.0)
        self.theta_line.setMaximum(180.0)
        self.theta_line.setSingleStep(0.1)
        self.theta_line.setObjectName("theta_line")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.theta_line)
        self.psi_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.psi_line.setDecimals(6)
        self.psi_line.setMinimum(-180.0)
        self.psi_line.setMaximum(180.0)
        self.psi_line.setSingleStep(0.1)
        self.psi_line.setObjectName("psi_line")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.psi_line)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 5, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 321, 156))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.k1_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.k1_line.setDecimals(6)
        self.k1_line.setMaximum(100000000000000.0)
        self.k1_line.setSingleStep(0.1)
        self.k1_line.setObjectName("k1_line")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.k1_line)
        self.k2_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.k2_line.setDecimals(6)
        self.k2_line.setMinimum(-1e+22)
        self.k2_line.setMaximum(1e+25)
        self.k2_line.setSingleStep(0.1)
        self.k2_line.setObjectName("k2_line")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.k2_line)
        self.k3_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.k3_line.setDecimals(6)
        self.k3_line.setMinimum(-1e+27)
        self.k3_line.setMaximum(1e+31)
        self.k3_line.setSingleStep(0.1)
        self.k3_line.setObjectName("k3_line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.k3_line)
        self.p2_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.p2_line.setDecimals(6)
        self.p2_line.setMinimum(-1e+23)
        self.p2_line.setMaximum(1000000000000000.0)
        self.p2_line.setSingleStep(0.1)
        self.p2_line.setObjectName("p2_line")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.p2_line)
        self.p1_line = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.p1_line.setDecimals(6)
        self.p1_line.setMinimum(-1e+24)
        self.p1_line.setMaximum(1e+20)
        self.p1_line.setSingleStep(0.1)
        self.p1_line.setObjectName("p1_line")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.p1_line)
        self.gridLayout.addWidget(self.groupBox_3, 7, 0, 3, 1)
        self.calibrate_btn = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/assets/icons/chessboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrate_btn.setIcon(icon2)
        self.calibrate_btn.setIconSize(QtCore.QSize(32, 32))
        self.calibrate_btn.setObjectName("calibrate_btn")
        self.gridLayout.addWidget(self.calibrate_btn, 6, 3, 1, 1)
        self.view_tab_window = QtWidgets.QTabWidget(self.centralwidget)
        self.view_tab_window.setMovable(True)
        self.view_tab_window.setObjectName("view_tab_window")
        self.view_tab = QtWidgets.QWidget()
        self.view_tab.setObjectName("view_tab")
        self.gview = QtWidgets.QGraphicsView(self.view_tab)
        self.gview.setGeometry(QtCore.QRect(0, 0, 971, 671))
        self.gview.setObjectName("gview")
        self.view_tab_window.addTab(self.view_tab, "")
        self.mask_tab = QtWidgets.QWidget()
        self.mask_tab.setObjectName("mask_tab")
        self.mask_view = QtWidgets.QGraphicsView(self.mask_tab)
        self.mask_view.setEnabled(True)
        self.mask_view.setGeometry(QtCore.QRect(-5, 1, 981, 721))
        self.mask_view.setObjectName("mask_view")
        self.view_tab_window.addTab(self.mask_tab, "")
        self.gridLayout.addWidget(self.view_tab_window, 0, 1, 12, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCamera = QtWidgets.QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMetadata = QtWidgets.QAction(MainWindow)
        self.actionMetadata.setObjectName("actionMetadata")
        self.action_save_parameters = QtWidgets.QAction(MainWindow)
        self.action_save_parameters.setObjectName("action_save_parameters")
        self.actionCalibrate = QtWidgets.QAction(MainWindow)
        self.actionCalibrate.setObjectName("actionCalibrate")
        self.action_calibrate = QtWidgets.QAction(MainWindow)
        self.action_calibrate.setCheckable(True)
        self.action_calibrate.setObjectName("action_calibrate")
        self.action_pnp = QtWidgets.QAction(MainWindow)
        self.action_pnp.setCheckable(True)
        self.action_pnp.setObjectName("action_pnp")
        self.action_track = QtWidgets.QAction(MainWindow)
        self.action_track.setCheckable(True)
        self.action_track.setObjectName("action_track")
        self.action_open_image = QtWidgets.QAction(MainWindow)
        self.action_open_image.setObjectName("action_open_image")
        self.action_open_camera = QtWidgets.QAction(MainWindow)
        self.action_open_camera.setObjectName("action_open_camera")
        self.action_save_fits = QtWidgets.QAction(MainWindow)
        self.action_save_fits.setObjectName("action_save_fits")
        self.action_load_parameters = QtWidgets.QAction(MainWindow)
        self.action_load_parameters.setObjectName("action_load_parameters")
        self.action_load_distortion_coefficients = QtWidgets.QAction(MainWindow)
        self.action_load_distortion_coefficients.setObjectName("action_load_distortion_coefficients")
        self.menuFile.addAction(self.action_open_image)
        self.menuFile.addAction(self.action_open_camera)
        self.menuFile.addAction(self.action_save_parameters)
        self.menuFile.addAction(self.action_load_parameters)
        self.menuFile.addAction(self.action_save_fits)
        self.menuFile.addAction(self.action_load_distortion_coefficients)
        self.menuCamera.addAction(self.actionMetadata)
        self.menuCamera.addAction(self.actionCalibrate)
        self.menuMode.addAction(self.action_calibrate)
        self.menuMode.addAction(self.action_pnp)
        self.menuMode.addAction(self.action_track)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(MainWindow)
        self.view_tab_window.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "camtrak"))
        self.solve_pnp_btn.setToolTip(_translate("MainWindow", "Solve PnP problem"))
        self.solve_pnp_btn.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Known World Points"))
        self.capture_btn.setToolTip(_translate("MainWindow", "Capture an image and save to disk."))
        self.image_type_box.setItemText(0, _translate("MainWindow", "BMP"))
        self.image_type_box.setItemText(1, _translate("MainWindow", "FITS"))
        self.image_type_box.setItemText(2, _translate("MainWindow", "PNG"))
        self.image_type_box.setItemText(3, _translate("MainWindow", "TIFF"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Camera Parameters"))
        self.label.setText(_translate("MainWindow", "Lat"))
        self.label_2.setText(_translate("MainWindow", "Lon"))
        self.label_3.setText(_translate("MainWindow", "Alt"))
        self.label_4.setText(_translate("MainWindow", "IFOV"))
        self.label_5.setText(_translate("MainWindow", "cx"))
        self.label_6.setText(_translate("MainWindow", "cy"))
        self.label_12.setText(_translate("MainWindow", "Phi"))
        self.label_13.setText(_translate("MainWindow", "Theta"))
        self.label_14.setText(_translate("MainWindow", "Psi"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Distortion Coeeficients"))
        self.label_7.setText(_translate("MainWindow", "k1"))
        self.label_8.setText(_translate("MainWindow", "k2"))
        self.label_9.setText(_translate("MainWindow", "k3"))
        self.label_10.setText(_translate("MainWindow", "p1"))
        self.label_11.setText(_translate("MainWindow", "p2"))
        self.calibrate_btn.setToolTip(_translate("MainWindow", "Run the calibration."))
        self.calibrate_btn.setText(_translate("MainWindow", "..."))
        self.view_tab_window.setTabText(self.view_tab_window.indexOf(self.view_tab), _translate("MainWindow", "view"))
        self.view_tab_window.setTabText(self.view_tab_window.indexOf(self.mask_tab), _translate("MainWindow", "mask"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCamera.setTitle(_translate("MainWindow", "Camera"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.actionMetadata.setText(_translate("MainWindow", "Metadata"))
        self.action_save_parameters.setText(_translate("MainWindow", "Save Parameters"))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate"))
        self.action_calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.action_pnp.setText(_translate("MainWindow", "PnP"))
        self.action_track.setText(_translate("MainWindow", "Track"))
        self.action_open_image.setText(_translate("MainWindow", "Open Image"))
        self.action_open_camera.setText(_translate("MainWindow", "Open Camera"))
        self.action_save_fits.setText(_translate("MainWindow", "Save FITS"))
        self.action_load_parameters.setText(_translate("MainWindow", "Load Parameters"))
        self.action_load_distortion_coefficients.setText(_translate("MainWindow", "Load Distortion Coefficients"))


from . import resources
