# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camtrak.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.known_points_table = QtWidgets.QTableView(self.centralwidget)
        self.known_points_table.setGeometry(QtCore.QRect(20, 10, 256, 271))
        self.known_points_table.setObjectName("known_points_table")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 290, 251, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.camera_lat_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.camera_lat_line.setObjectName("camera_lat_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera_lat_line)
        self.camera_lon_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.camera_lon_line.setObjectName("camera_lon_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera_lon_line)
        self.camera_alt_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.camera_alt_line.setObjectName("camera_alt_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera_alt_line)
        self.ifov_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ifov_line.setObjectName("ifov_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ifov_line)
        self.cx_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cx_line.setObjectName("cx_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cx_line)
        self.cy_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cy_line.setObjectName("cy_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cy_line)
        self.gview = QtWidgets.QGraphicsView(self.centralwidget)
        self.gview.setGeometry(QtCore.QRect(290, 10, 721, 541))
        self.gview.setObjectName("gview")
        self.capture_btn = QtWidgets.QPushButton(self.centralwidget)
        self.capture_btn.setGeometry(QtCore.QRect(920, 560, 89, 25))
        self.capture_btn.setObjectName("capture_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCamera = QtWidgets.QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMetadata = QtWidgets.QAction(MainWindow)
        self.actionMetadata.setObjectName("actionMetadata")
        self.actionSave_Parameters = QtWidgets.QAction(MainWindow)
        self.actionSave_Parameters.setObjectName("actionSave_Parameters")
        self.actionCalibrate = QtWidgets.QAction(MainWindow)
        self.actionCalibrate.setObjectName("actionCalibrate")
        self.menuFile.addAction(self.actionSave_Parameters)
        self.menuCamera.addAction(self.actionMetadata)
        self.menuCamera.addAction(self.actionCalibrate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "camtrak"))
        self.label.setText(_translate("MainWindow", "Lat"))
        self.label_2.setText(_translate("MainWindow", "Lon"))
        self.label_3.setText(_translate("MainWindow", "Alt"))
        self.label_4.setText(_translate("MainWindow", "IFOV"))
        self.label_5.setText(_translate("MainWindow", "cx"))
        self.label_6.setText(_translate("MainWindow", "cy"))
        self.capture_btn.setText(_translate("MainWindow", "Capture"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCamera.setTitle(_translate("MainWindow", "Camera"))
        self.actionMetadata.setText(_translate("MainWindow", "Metadata"))
        self.actionSave_Parameters.setText(_translate("MainWindow", "Save Parameters"))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate"))

